/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Message, messageSchema } from './message';
import { PrivateKey, privateKeySchema } from './privateKey';

export interface CreateSignRequest {
  message: Message;
  privateKey: PrivateKey;
}

export const createSignRequestSchema: Schema<CreateSignRequest> = object({
  message: ['message', lazy(() => messageSchema)],
  privateKey: ['private_key', lazy(() => privateKeySchema)],
});
