/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { License, licenseSchema } from './license';

export interface CredentialSubject {
  id: string;
  license: License;
}

export const credentialSubjectSchema: Schema<CredentialSubject> = object({
  id: ['id', string()],
  license: ['License', lazy(() => licenseSchema)],
});
