/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface License {
  type: string;
  dLNumber: string;
}

export const licenseSchema: Schema<License> = object({
  type: ['type', string()],
  dLNumber: ['DLNumber', string()],
});
