/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Message {
  mobileNumber: string;
}

export const messageSchema: Schema<Message> = object({
  mobileNumber: ['Mobile Number', string()],
});
