/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Proof {
  type: string;
  created: string;
  jws: string;
  proofPurpose: string;
  verificationMethod: string;
}

export const proofSchema: Schema<Proof> = object({
  type: ['type', string()],
  created: ['created', string()],
  jws: ['jws', string()],
  proofPurpose: ['proofPurpose', string()],
  verificationMethod: ['verificationMethod', string()],
});
