/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PublicKey {
  kty: string;
  crv: string;
  x: string;
  y: string;
}

export const publicKeySchema: Schema<PublicKey> = object({
  kty: ['kty', string()],
  crv: ['crv', string()],
  x: ['x', string()],
  y: ['y', string()],
});
