/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface QRCodeRequest {
  name: string;
  age: number;
  department: string;
  id: string;
}

export const qRCodeRequestSchema: Schema<QRCodeRequest> = object({
  name: ['name', string()],
  age: ['age', number()],
  department: ['department', string()],
  id: ['id', string()],
});
