/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { PublicKey, publicKeySchema } from './publicKey';

export interface VerifySignRequest {
  publicKey: PublicKey;
}

export const verifySignRequestSchema: Schema<VerifySignRequest> = object({
  publicKey: ['public_key', lazy(() => publicKeySchema)],
});
