/**
 * HackNHustle ION-DIDLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import {
  CredentialSubject,
  credentialSubjectSchema,
} from './credentialSubject';
import { Proof, proofSchema } from './proof';

export interface VerifiableCredential {
  context: string[];
  id: string;
  type: string[];
  issuer: string;
  issuanceDate: string;
  credentialSubject: CredentialSubject;
  proof: Proof;
}

export const verifiableCredentialSchema: Schema<VerifiableCredential> = object({
  context: ['@context', array(string())],
  id: ['id', string()],
  type: ['type', array(string())],
  issuer: ['issuer', string()],
  issuanceDate: ['issuanceDate', string()],
  credentialSubject: ['credentialSubject', lazy(() => credentialSubjectSchema)],
  proof: ['proof', lazy(() => proofSchema)],
});
